export const FETCHING_PRODUCTS = "FETCHING_PRODUCTS";
export const FETCHING_PRODUCTS_SUCCESS = "FETCHING_PRODUCTS_SUCCESS";
export const FETCHING_PRODUCTS_FAILURE = "FETCHING_PRODUCTS_FAILURE";

export const PRODUCT_ADDED_TO_RECIPE = "PRODUCT_ADDED_TO_RECIPE";
