export const FETCHING_PRODUCTS = "FETCHING_PRODUCTS";
export const FETCHING_PRODUCTS_SUCCESS = "FETCHING_PRODUCTS_SUCCESS";
export const FETCHING_PRODUCTS_FAILURE = "FETCHING_PRODUCTS_FAILURE";

export const ITEM_ADDED_TO_CART = "ITEM_ADDED_TO_CART";
export const ITEM_DELETED_FROM_CART = "ITEM_DELETED_FROM_CART";
export const ITEM_MARKED_ON_CART = "ITEM_MARKED_ON_CART";

export const LIST_ADDED = "LIST_ADDED";
export const LIST_DELETED = "LIST_DELETED";
