export const FETCHING_PRODUCTS = "FETCHING_PRODUCTS";
export const FETCHING_PRODUCTS_SUCCESS = "FETCHING_PRODUCTS_SUCCESS";
export const FETCHING_PRODUCTS_FAILURE = "FETCHING_PRODUCTS_FAILURE";

export const ITEM_ADDED_TO_CART = "ITEM_ADDED_TO_CART";
export const ITEM_DELETED_FROM_CART = "ITEM_DELETED_FROM_CART";
export const ITEM_MARKED_ON_CART = "ITEM_MARKED_ON_CART";

export const LIST_ADDED = "LIST_ADDED";
export const LIST_DELETED = "LIST_DELETED";

export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const SHOW_ALL = "SHOW_ALL";
export const SHOW_MARKED = "SHOW_MARKED";
export const SHOW_ACTIVE = "SHOW_ACTIVE";
